name: 'Branch Naming Convention'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  branch-naming:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check Branch Name'
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          # This regex pattern requires branches to start with feature/, fix/, chore/, or docs/
          REGEX_PATTERN="^(feature|fix|chore|docs)\/.*"

          if [[ $BRANCH_NAME =~ $REGEX_PATTERN ]]; then
            echo "Branch name '${BRANCH_NAME}' is valid."
            exit 0
          else
            echo "Error: Branch name '${BRANCH_NAME}' does not follow the required convention."
            echo "Please name your branch starting with 'feature/', 'fix/', 'chore/', or 'docs/'."
            exit 1
          fi
